### ISSUE TITLE
Colour changes for current and past events.

### ISSUE THREAD

**Issue by Crazymoomin** [SmartPaws/smartpaws-android#11]
Implement a visual indication via a change of font colour and/or style on an event card if event is currently running or in the past.

**Comment by Crazymoomin** [comment]
Now implemented as of 2bdc422fdc502e1ba9842000fba179631e4abd40, exact implementation still being finalised.

**Comment by toastedtruth** [comment]
Can you test this against the most recent commits?

**Comment by Crazymoomin** [comment]
Can do. 2bdc422fdc502e1ba9842000fba179631e4abd40 was the first implementation, I redid it as of e2a6dc3bb892c07222fedeca2196f38f1d0be696. Will merge upstream again and test.
