### ISSUE TITLE
Hide fragment content until all data has downloaded fully

### ISSUE THREAD

**Issue by toastedtruth** [SmartPaws/smartpaws-android#3]
Images currently display long after the JSON content of the fragment has been loaded. Show a spinning 'loading' style icon until the content has loaded.

**Comment by Crazymoomin** [comment]
Should we have an icon for each `RecyclerView` too? That can take a while to load when first displayed.

**Comment by toastedtruth** [comment]
See #3

**Comment by toastedtruth** [comment]
That is the plan :)

**Comment by toastedtruth** [comment]
Issue has been resolved with the use of an HTTP library and ViewPager. Still working on this, but it's safe to close the issue.
