### ISSUE TITLE
Add a maps section

### ISSUE THREAD

**Issue by toastedtruth** [SmartPaws/smartpaws-android#4]
Maps of the local area and convention space should be within this fragment.

Possibly implement it by using Google Indoor Maps? This will be a fantastic addition. However, it would require retrieving the maps from each convention hotel, and asking for their permission to use it. 
https://www.google.com/maps/about/partners/indoormaps/

**Comment by toastedtruth** [comment]
Since the Hilton Metropole is considered a non-public space, Google Indoor Maps is now out of the question

**Comment by Crazymoomin** [comment]
I could make a vector copy of the official map, maybe in a more "smartpawsy" style.

**Comment by toastedtruth** [comment]
The problem with vector based SVGs is there is a lack of support for them below KitKat. A resizable ImageView is another solution, but they look a bit outdated (Gingerbread UI).

**Comment by Crazymoomin** [comment]
What options are there for vectors below KK?

**Comment by toastedtruth** [comment]
External libraries are about your only option. Even if you did manage to load an SVG, you would still have to display it inside some sort of ImageView

**Comment by toastedtruth** [comment]
You could, potentially, load this section using WebView and HTML5 + CSS3

**Comment by toastedtruth** [comment]
Commit 006d89b95d0fda77b125633024b3f6524f004b03 
Basic implementation of this is now in place. Ideally would like to add a ViewPager, and the Dealers' Den map. Will talk internally with ConFuzzled staff, or pull the maps from the website.
